name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set environment variables
      env:
        API_KEY: ${{ secrets.API_KEY }}
    - name: Build and Deploy
      run: |
        # build and deploy steps go here
